number = 6
slug = "unless-minted-syntax-green"
status = "completed"
description = """
# Step: unless-minted-syntax-green

Generalize minted syntax support so the u..."""
role = "production"
context_files = []
created_at = "2026-04-28T16:59:12"
completed_at = "2026-04-29T09:05:53"
commits = ["566335ef2c4dd4ba6bf46bdb6623b8b5f310c606"]
