number = 4
slug = "interp-power-2-8-green"
status = "completed"
description = """
# Step: interp-power-2-8-green

Implement the minimal reference interpreter p..."""
role = "production"
context_files = []
created_at = "2026-04-28T11:23:22"
completed_at = "2026-04-28T11:55:48"
commits = ["ab0bcf80f845e0806fe336aa292263a8a74d367a"]
